//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::Fees;
use crate::generated::types::LastOrderDistance;
use crate::generated::types::NeedTake;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_pubkey::Pubkey;

/// Accounts.
#[derive(Debug)]
pub struct SetParams {
    pub token_program: solana_pubkey::Pubkey,

    pub amm: solana_pubkey::Pubkey,

    pub amm_authority: solana_pubkey::Pubkey,

    pub amm_open_orders: solana_pubkey::Pubkey,

    pub amm_target_orders: solana_pubkey::Pubkey,

    pub amm_coin_vault: solana_pubkey::Pubkey,

    pub amm_pc_vault: solana_pubkey::Pubkey,

    pub serum_program: solana_pubkey::Pubkey,

    pub serum_market: solana_pubkey::Pubkey,

    pub serum_coin_vault: solana_pubkey::Pubkey,

    pub serum_pc_vault: solana_pubkey::Pubkey,

    pub serum_vault_signer: solana_pubkey::Pubkey,

    pub serum_event_queue: solana_pubkey::Pubkey,

    pub serum_bids: solana_pubkey::Pubkey,

    pub serum_asks: solana_pubkey::Pubkey,

    pub amm_admin_account: solana_pubkey::Pubkey,
}

impl SetParams {
    pub fn instruction(&self, args: SetParamsInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SetParamsInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(16 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.amm, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.amm_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.amm_open_orders,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.amm_target_orders,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.amm_coin_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.amm_pc_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.serum_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_market,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_coin_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_pc_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.serum_vault_signer,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_event_queue,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.serum_bids, false));
        accounts.push(solana_instruction::AccountMeta::new(self.serum_asks, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.amm_admin_account,
            true,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&SetParamsInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::RAYDIUM_AMM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetParamsInstructionData {
    discriminator: [u8; 1],
}

impl SetParamsInstructionData {
    pub fn new() -> Self {
        Self { discriminator: [6] }
    }
}

impl Default for SetParamsInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetParamsInstructionArgs {
    pub param: u8,
    pub value: Option<u64>,
    pub new_pubkey: Option<Pubkey>,
    pub fees: Option<Fees>,
    pub last_order_distance: Option<LastOrderDistance>,
    pub need_take_amounts: Option<NeedTake>,
}

/// Instruction builder for `SetParams`.
///
/// ### Accounts:
///
///   0. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   1. `[writable]` amm
///   2. `[]` amm_authority
///   3. `[writable]` amm_open_orders
///   4. `[writable]` amm_target_orders
///   5. `[writable]` amm_coin_vault
///   6. `[writable]` amm_pc_vault
///   7. `[]` serum_program
///   8. `[writable]` serum_market
///   9. `[writable]` serum_coin_vault
///   10. `[writable]` serum_pc_vault
///   11. `[]` serum_vault_signer
///   12. `[writable]` serum_event_queue
///   13. `[writable]` serum_bids
///   14. `[writable]` serum_asks
///   15. `[signer]` amm_admin_account
#[derive(Clone, Debug, Default)]
pub struct SetParamsBuilder {
    token_program: Option<solana_pubkey::Pubkey>,
    amm: Option<solana_pubkey::Pubkey>,
    amm_authority: Option<solana_pubkey::Pubkey>,
    amm_open_orders: Option<solana_pubkey::Pubkey>,
    amm_target_orders: Option<solana_pubkey::Pubkey>,
    amm_coin_vault: Option<solana_pubkey::Pubkey>,
    amm_pc_vault: Option<solana_pubkey::Pubkey>,
    serum_program: Option<solana_pubkey::Pubkey>,
    serum_market: Option<solana_pubkey::Pubkey>,
    serum_coin_vault: Option<solana_pubkey::Pubkey>,
    serum_pc_vault: Option<solana_pubkey::Pubkey>,
    serum_vault_signer: Option<solana_pubkey::Pubkey>,
    serum_event_queue: Option<solana_pubkey::Pubkey>,
    serum_bids: Option<solana_pubkey::Pubkey>,
    serum_asks: Option<solana_pubkey::Pubkey>,
    amm_admin_account: Option<solana_pubkey::Pubkey>,
    param: Option<u8>,
    value: Option<u64>,
    new_pubkey: Option<Pubkey>,
    fees: Option<Fees>,
    last_order_distance: Option<LastOrderDistance>,
    need_take_amounts: Option<NeedTake>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SetParamsBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn amm(&mut self, amm: solana_pubkey::Pubkey) -> &mut Self {
        self.amm = Some(amm);
        self
    }
    #[inline(always)]
    pub fn amm_authority(&mut self, amm_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_authority = Some(amm_authority);
        self
    }
    #[inline(always)]
    pub fn amm_open_orders(&mut self, amm_open_orders: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_open_orders = Some(amm_open_orders);
        self
    }
    #[inline(always)]
    pub fn amm_target_orders(&mut self, amm_target_orders: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_target_orders = Some(amm_target_orders);
        self
    }
    #[inline(always)]
    pub fn amm_coin_vault(&mut self, amm_coin_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_coin_vault = Some(amm_coin_vault);
        self
    }
    #[inline(always)]
    pub fn amm_pc_vault(&mut self, amm_pc_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_pc_vault = Some(amm_pc_vault);
        self
    }
    #[inline(always)]
    pub fn serum_program(&mut self, serum_program: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_program = Some(serum_program);
        self
    }
    #[inline(always)]
    pub fn serum_market(&mut self, serum_market: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_market = Some(serum_market);
        self
    }
    #[inline(always)]
    pub fn serum_coin_vault(&mut self, serum_coin_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_coin_vault = Some(serum_coin_vault);
        self
    }
    #[inline(always)]
    pub fn serum_pc_vault(&mut self, serum_pc_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_pc_vault = Some(serum_pc_vault);
        self
    }
    #[inline(always)]
    pub fn serum_vault_signer(&mut self, serum_vault_signer: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_vault_signer = Some(serum_vault_signer);
        self
    }
    #[inline(always)]
    pub fn serum_event_queue(&mut self, serum_event_queue: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_event_queue = Some(serum_event_queue);
        self
    }
    #[inline(always)]
    pub fn serum_bids(&mut self, serum_bids: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_bids = Some(serum_bids);
        self
    }
    #[inline(always)]
    pub fn serum_asks(&mut self, serum_asks: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_asks = Some(serum_asks);
        self
    }
    #[inline(always)]
    pub fn amm_admin_account(&mut self, amm_admin_account: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_admin_account = Some(amm_admin_account);
        self
    }
    #[inline(always)]
    pub fn param(&mut self, param: u8) -> &mut Self {
        self.param = Some(param);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn value(&mut self, value: u64) -> &mut Self {
        self.value = Some(value);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn new_pubkey(&mut self, new_pubkey: Pubkey) -> &mut Self {
        self.new_pubkey = Some(new_pubkey);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn fees(&mut self, fees: Fees) -> &mut Self {
        self.fees = Some(fees);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn last_order_distance(&mut self, last_order_distance: LastOrderDistance) -> &mut Self {
        self.last_order_distance = Some(last_order_distance);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn need_take_amounts(&mut self, need_take_amounts: NeedTake) -> &mut Self {
        self.need_take_amounts = Some(need_take_amounts);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = SetParams {
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            amm: self.amm.expect("amm is not set"),
            amm_authority: self.amm_authority.expect("amm_authority is not set"),
            amm_open_orders: self.amm_open_orders.expect("amm_open_orders is not set"),
            amm_target_orders: self
                .amm_target_orders
                .expect("amm_target_orders is not set"),
            amm_coin_vault: self.amm_coin_vault.expect("amm_coin_vault is not set"),
            amm_pc_vault: self.amm_pc_vault.expect("amm_pc_vault is not set"),
            serum_program: self.serum_program.expect("serum_program is not set"),
            serum_market: self.serum_market.expect("serum_market is not set"),
            serum_coin_vault: self.serum_coin_vault.expect("serum_coin_vault is not set"),
            serum_pc_vault: self.serum_pc_vault.expect("serum_pc_vault is not set"),
            serum_vault_signer: self
                .serum_vault_signer
                .expect("serum_vault_signer is not set"),
            serum_event_queue: self
                .serum_event_queue
                .expect("serum_event_queue is not set"),
            serum_bids: self.serum_bids.expect("serum_bids is not set"),
            serum_asks: self.serum_asks.expect("serum_asks is not set"),
            amm_admin_account: self
                .amm_admin_account
                .expect("amm_admin_account is not set"),
        };
        let args = SetParamsInstructionArgs {
            param: self.param.clone().expect("param is not set"),
            value: self.value.clone(),
            new_pubkey: self.new_pubkey.clone(),
            fees: self.fees.clone(),
            last_order_distance: self.last_order_distance.clone(),
            need_take_amounts: self.need_take_amounts.clone(),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `set_params` CPI accounts.
pub struct SetParamsCpiAccounts<'a, 'b> {
    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub amm: &'b solana_account_info::AccountInfo<'a>,

    pub amm_authority: &'b solana_account_info::AccountInfo<'a>,

    pub amm_open_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_target_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_coin_vault: &'b solana_account_info::AccountInfo<'a>,

    pub amm_pc_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_program: &'b solana_account_info::AccountInfo<'a>,

    pub serum_market: &'b solana_account_info::AccountInfo<'a>,

    pub serum_coin_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_pc_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,

    pub serum_event_queue: &'b solana_account_info::AccountInfo<'a>,

    pub serum_bids: &'b solana_account_info::AccountInfo<'a>,

    pub serum_asks: &'b solana_account_info::AccountInfo<'a>,

    pub amm_admin_account: &'b solana_account_info::AccountInfo<'a>,
}

/// `set_params` CPI instruction.
pub struct SetParamsCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub amm: &'b solana_account_info::AccountInfo<'a>,

    pub amm_authority: &'b solana_account_info::AccountInfo<'a>,

    pub amm_open_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_target_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_coin_vault: &'b solana_account_info::AccountInfo<'a>,

    pub amm_pc_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_program: &'b solana_account_info::AccountInfo<'a>,

    pub serum_market: &'b solana_account_info::AccountInfo<'a>,

    pub serum_coin_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_pc_vault: &'b solana_account_info::AccountInfo<'a>,

    pub serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,

    pub serum_event_queue: &'b solana_account_info::AccountInfo<'a>,

    pub serum_bids: &'b solana_account_info::AccountInfo<'a>,

    pub serum_asks: &'b solana_account_info::AccountInfo<'a>,

    pub amm_admin_account: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SetParamsInstructionArgs,
}

impl<'a, 'b> SetParamsCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SetParamsCpiAccounts<'a, 'b>,
        args: SetParamsInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            token_program: accounts.token_program,
            amm: accounts.amm,
            amm_authority: accounts.amm_authority,
            amm_open_orders: accounts.amm_open_orders,
            amm_target_orders: accounts.amm_target_orders,
            amm_coin_vault: accounts.amm_coin_vault,
            amm_pc_vault: accounts.amm_pc_vault,
            serum_program: accounts.serum_program,
            serum_market: accounts.serum_market,
            serum_coin_vault: accounts.serum_coin_vault,
            serum_pc_vault: accounts.serum_pc_vault,
            serum_vault_signer: accounts.serum_vault_signer,
            serum_event_queue: accounts.serum_event_queue,
            serum_bids: accounts.serum_bids,
            serum_asks: accounts.serum_asks,
            amm_admin_account: accounts.amm_admin_account,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(16 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.amm.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.amm_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.amm_open_orders.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.amm_target_orders.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.amm_coin_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.amm_pc_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.serum_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_market.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_coin_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_pc_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.serum_vault_signer.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_event_queue.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_bids.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_asks.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.amm_admin_account.key,
            true,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&SetParamsInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::RAYDIUM_AMM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(17 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.amm.clone());
        account_infos.push(self.amm_authority.clone());
        account_infos.push(self.amm_open_orders.clone());
        account_infos.push(self.amm_target_orders.clone());
        account_infos.push(self.amm_coin_vault.clone());
        account_infos.push(self.amm_pc_vault.clone());
        account_infos.push(self.serum_program.clone());
        account_infos.push(self.serum_market.clone());
        account_infos.push(self.serum_coin_vault.clone());
        account_infos.push(self.serum_pc_vault.clone());
        account_infos.push(self.serum_vault_signer.clone());
        account_infos.push(self.serum_event_queue.clone());
        account_infos.push(self.serum_bids.clone());
        account_infos.push(self.serum_asks.clone());
        account_infos.push(self.amm_admin_account.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SetParams` via CPI.
///
/// ### Accounts:
///
///   0. `[]` token_program
///   1. `[writable]` amm
///   2. `[]` amm_authority
///   3. `[writable]` amm_open_orders
///   4. `[writable]` amm_target_orders
///   5. `[writable]` amm_coin_vault
///   6. `[writable]` amm_pc_vault
///   7. `[]` serum_program
///   8. `[writable]` serum_market
///   9. `[writable]` serum_coin_vault
///   10. `[writable]` serum_pc_vault
///   11. `[]` serum_vault_signer
///   12. `[writable]` serum_event_queue
///   13. `[writable]` serum_bids
///   14. `[writable]` serum_asks
///   15. `[signer]` amm_admin_account
#[derive(Clone, Debug)]
pub struct SetParamsCpiBuilder<'a, 'b> {
    instruction: Box<SetParamsCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SetParamsCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SetParamsCpiBuilderInstruction {
            __program: program,
            token_program: None,
            amm: None,
            amm_authority: None,
            amm_open_orders: None,
            amm_target_orders: None,
            amm_coin_vault: None,
            amm_pc_vault: None,
            serum_program: None,
            serum_market: None,
            serum_coin_vault: None,
            serum_pc_vault: None,
            serum_vault_signer: None,
            serum_event_queue: None,
            serum_bids: None,
            serum_asks: None,
            amm_admin_account: None,
            param: None,
            value: None,
            new_pubkey: None,
            fees: None,
            last_order_distance: None,
            need_take_amounts: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn amm(&mut self, amm: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.amm = Some(amm);
        self
    }
    #[inline(always)]
    pub fn amm_authority(
        &mut self,
        amm_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_authority = Some(amm_authority);
        self
    }
    #[inline(always)]
    pub fn amm_open_orders(
        &mut self,
        amm_open_orders: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_open_orders = Some(amm_open_orders);
        self
    }
    #[inline(always)]
    pub fn amm_target_orders(
        &mut self,
        amm_target_orders: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_target_orders = Some(amm_target_orders);
        self
    }
    #[inline(always)]
    pub fn amm_coin_vault(
        &mut self,
        amm_coin_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_coin_vault = Some(amm_coin_vault);
        self
    }
    #[inline(always)]
    pub fn amm_pc_vault(
        &mut self,
        amm_pc_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_pc_vault = Some(amm_pc_vault);
        self
    }
    #[inline(always)]
    pub fn serum_program(
        &mut self,
        serum_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_program = Some(serum_program);
        self
    }
    #[inline(always)]
    pub fn serum_market(
        &mut self,
        serum_market: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_market = Some(serum_market);
        self
    }
    #[inline(always)]
    pub fn serum_coin_vault(
        &mut self,
        serum_coin_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_coin_vault = Some(serum_coin_vault);
        self
    }
    #[inline(always)]
    pub fn serum_pc_vault(
        &mut self,
        serum_pc_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_pc_vault = Some(serum_pc_vault);
        self
    }
    #[inline(always)]
    pub fn serum_vault_signer(
        &mut self,
        serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_vault_signer = Some(serum_vault_signer);
        self
    }
    #[inline(always)]
    pub fn serum_event_queue(
        &mut self,
        serum_event_queue: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_event_queue = Some(serum_event_queue);
        self
    }
    #[inline(always)]
    pub fn serum_bids(
        &mut self,
        serum_bids: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_bids = Some(serum_bids);
        self
    }
    #[inline(always)]
    pub fn serum_asks(
        &mut self,
        serum_asks: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_asks = Some(serum_asks);
        self
    }
    #[inline(always)]
    pub fn amm_admin_account(
        &mut self,
        amm_admin_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_admin_account = Some(amm_admin_account);
        self
    }
    #[inline(always)]
    pub fn param(&mut self, param: u8) -> &mut Self {
        self.instruction.param = Some(param);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn value(&mut self, value: u64) -> &mut Self {
        self.instruction.value = Some(value);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn new_pubkey(&mut self, new_pubkey: Pubkey) -> &mut Self {
        self.instruction.new_pubkey = Some(new_pubkey);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn fees(&mut self, fees: Fees) -> &mut Self {
        self.instruction.fees = Some(fees);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn last_order_distance(&mut self, last_order_distance: LastOrderDistance) -> &mut Self {
        self.instruction.last_order_distance = Some(last_order_distance);
        self
    }
    /// `[optional argument]`
    #[inline(always)]
    pub fn need_take_amounts(&mut self, need_take_amounts: NeedTake) -> &mut Self {
        self.instruction.need_take_amounts = Some(need_take_amounts);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = SetParamsInstructionArgs {
            param: self.instruction.param.clone().expect("param is not set"),
            value: self.instruction.value.clone(),
            new_pubkey: self.instruction.new_pubkey.clone(),
            fees: self.instruction.fees.clone(),
            last_order_distance: self.instruction.last_order_distance.clone(),
            need_take_amounts: self.instruction.need_take_amounts.clone(),
        };
        let instruction = SetParamsCpi {
            __program: self.instruction.__program,

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            amm: self.instruction.amm.expect("amm is not set"),

            amm_authority: self
                .instruction
                .amm_authority
                .expect("amm_authority is not set"),

            amm_open_orders: self
                .instruction
                .amm_open_orders
                .expect("amm_open_orders is not set"),

            amm_target_orders: self
                .instruction
                .amm_target_orders
                .expect("amm_target_orders is not set"),

            amm_coin_vault: self
                .instruction
                .amm_coin_vault
                .expect("amm_coin_vault is not set"),

            amm_pc_vault: self
                .instruction
                .amm_pc_vault
                .expect("amm_pc_vault is not set"),

            serum_program: self
                .instruction
                .serum_program
                .expect("serum_program is not set"),

            serum_market: self
                .instruction
                .serum_market
                .expect("serum_market is not set"),

            serum_coin_vault: self
                .instruction
                .serum_coin_vault
                .expect("serum_coin_vault is not set"),

            serum_pc_vault: self
                .instruction
                .serum_pc_vault
                .expect("serum_pc_vault is not set"),

            serum_vault_signer: self
                .instruction
                .serum_vault_signer
                .expect("serum_vault_signer is not set"),

            serum_event_queue: self
                .instruction
                .serum_event_queue
                .expect("serum_event_queue is not set"),

            serum_bids: self.instruction.serum_bids.expect("serum_bids is not set"),

            serum_asks: self.instruction.serum_asks.expect("serum_asks is not set"),

            amm_admin_account: self
                .instruction
                .amm_admin_account
                .expect("amm_admin_account is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SetParamsCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_open_orders: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_target_orders: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_coin_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_pc_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_market: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_coin_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_pc_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_vault_signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_event_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_bids: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_asks: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_admin_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    param: Option<u8>,
    value: Option<u64>,
    new_pubkey: Option<Pubkey>,
    fees: Option<Fees>,
    last_order_distance: Option<LastOrderDistance>,
    need_take_amounts: Option<NeedTake>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
