//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const SWAP_BASE_IN_DISCRIMINATOR: [u8; 1] = [9];

/// Accounts.
#[derive(Debug)]
pub struct SwapBaseIn {
    pub token_program: solana_pubkey::Pubkey,

    pub amm: solana_pubkey::Pubkey,

    pub amm_authority: solana_pubkey::Pubkey,

    pub amm_open_orders: solana_pubkey::Pubkey,

    pub amm_target_orders: Option<solana_pubkey::Pubkey>,

    pub pool_coin_token_account: solana_pubkey::Pubkey,

    pub pool_pc_token_account: solana_pubkey::Pubkey,

    pub serum_program: solana_pubkey::Pubkey,

    pub serum_market: solana_pubkey::Pubkey,

    pub serum_bids: solana_pubkey::Pubkey,

    pub serum_asks: solana_pubkey::Pubkey,

    pub serum_event_queue: solana_pubkey::Pubkey,

    pub serum_coin_vault_account: solana_pubkey::Pubkey,

    pub serum_pc_vault_account: solana_pubkey::Pubkey,

    pub serum_vault_signer: solana_pubkey::Pubkey,

    pub uer_source_token_account: solana_pubkey::Pubkey,

    pub uer_destination_token_account: solana_pubkey::Pubkey,

    pub user_source_owner: solana_pubkey::Pubkey,
}

impl SwapBaseIn {
    pub fn instruction(&self, args: SwapBaseInInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SwapBaseInInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(18 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.amm, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.amm_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.amm_open_orders,
            false,
        ));
        if let Some(amm_target_orders) = self.amm_target_orders {
            accounts.push(solana_instruction::AccountMeta::new(
                amm_target_orders,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_coin_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_pc_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.serum_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_market,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.serum_bids, false));
        accounts.push(solana_instruction::AccountMeta::new(self.serum_asks, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_event_queue,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_coin_vault_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.serum_pc_vault_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.serum_vault_signer,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.uer_source_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.uer_destination_token_account,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.user_source_owner,
            true,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = borsh::to_vec(&SwapBaseInInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::RAYDIUM_AMM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapBaseInInstructionData {
    discriminator: [u8; 1],
}

impl SwapBaseInInstructionData {
    pub fn new() -> Self {
        Self { discriminator: [9] }
    }
}

impl Default for SwapBaseInInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapBaseInInstructionArgs {
    pub amount_in: u64,
    pub minimum_amount_out: u64,
}

/// Instruction builder for `SwapBaseIn`.
///
/// ### Accounts:
///
///   0. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   1. `[writable]` amm
///   2. `[]` amm_authority
///   3. `[writable]` amm_open_orders
///   4. `[writable, optional]` amm_target_orders
///   5. `[writable]` pool_coin_token_account
///   6. `[writable]` pool_pc_token_account
///   7. `[]` serum_program
///   8. `[writable]` serum_market
///   9. `[writable]` serum_bids
///   10. `[writable]` serum_asks
///   11. `[writable]` serum_event_queue
///   12. `[writable]` serum_coin_vault_account
///   13. `[writable]` serum_pc_vault_account
///   14. `[]` serum_vault_signer
///   15. `[writable]` uer_source_token_account
///   16. `[writable]` uer_destination_token_account
///   17. `[signer]` user_source_owner
#[derive(Clone, Debug, Default)]
pub struct SwapBaseInBuilder {
    token_program: Option<solana_pubkey::Pubkey>,
    amm: Option<solana_pubkey::Pubkey>,
    amm_authority: Option<solana_pubkey::Pubkey>,
    amm_open_orders: Option<solana_pubkey::Pubkey>,
    amm_target_orders: Option<solana_pubkey::Pubkey>,
    pool_coin_token_account: Option<solana_pubkey::Pubkey>,
    pool_pc_token_account: Option<solana_pubkey::Pubkey>,
    serum_program: Option<solana_pubkey::Pubkey>,
    serum_market: Option<solana_pubkey::Pubkey>,
    serum_bids: Option<solana_pubkey::Pubkey>,
    serum_asks: Option<solana_pubkey::Pubkey>,
    serum_event_queue: Option<solana_pubkey::Pubkey>,
    serum_coin_vault_account: Option<solana_pubkey::Pubkey>,
    serum_pc_vault_account: Option<solana_pubkey::Pubkey>,
    serum_vault_signer: Option<solana_pubkey::Pubkey>,
    uer_source_token_account: Option<solana_pubkey::Pubkey>,
    uer_destination_token_account: Option<solana_pubkey::Pubkey>,
    user_source_owner: Option<solana_pubkey::Pubkey>,
    amount_in: Option<u64>,
    minimum_amount_out: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SwapBaseInBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn amm(&mut self, amm: solana_pubkey::Pubkey) -> &mut Self {
        self.amm = Some(amm);
        self
    }
    #[inline(always)]
    pub fn amm_authority(&mut self, amm_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_authority = Some(amm_authority);
        self
    }
    #[inline(always)]
    pub fn amm_open_orders(&mut self, amm_open_orders: solana_pubkey::Pubkey) -> &mut Self {
        self.amm_open_orders = Some(amm_open_orders);
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn amm_target_orders(
        &mut self,
        amm_target_orders: Option<solana_pubkey::Pubkey>,
    ) -> &mut Self {
        self.amm_target_orders = amm_target_orders;
        self
    }
    #[inline(always)]
    pub fn pool_coin_token_account(
        &mut self,
        pool_coin_token_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.pool_coin_token_account = Some(pool_coin_token_account);
        self
    }
    #[inline(always)]
    pub fn pool_pc_token_account(
        &mut self,
        pool_pc_token_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.pool_pc_token_account = Some(pool_pc_token_account);
        self
    }
    #[inline(always)]
    pub fn serum_program(&mut self, serum_program: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_program = Some(serum_program);
        self
    }
    #[inline(always)]
    pub fn serum_market(&mut self, serum_market: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_market = Some(serum_market);
        self
    }
    #[inline(always)]
    pub fn serum_bids(&mut self, serum_bids: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_bids = Some(serum_bids);
        self
    }
    #[inline(always)]
    pub fn serum_asks(&mut self, serum_asks: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_asks = Some(serum_asks);
        self
    }
    #[inline(always)]
    pub fn serum_event_queue(&mut self, serum_event_queue: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_event_queue = Some(serum_event_queue);
        self
    }
    #[inline(always)]
    pub fn serum_coin_vault_account(
        &mut self,
        serum_coin_vault_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.serum_coin_vault_account = Some(serum_coin_vault_account);
        self
    }
    #[inline(always)]
    pub fn serum_pc_vault_account(
        &mut self,
        serum_pc_vault_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.serum_pc_vault_account = Some(serum_pc_vault_account);
        self
    }
    #[inline(always)]
    pub fn serum_vault_signer(&mut self, serum_vault_signer: solana_pubkey::Pubkey) -> &mut Self {
        self.serum_vault_signer = Some(serum_vault_signer);
        self
    }
    #[inline(always)]
    pub fn uer_source_token_account(
        &mut self,
        uer_source_token_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.uer_source_token_account = Some(uer_source_token_account);
        self
    }
    #[inline(always)]
    pub fn uer_destination_token_account(
        &mut self,
        uer_destination_token_account: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.uer_destination_token_account = Some(uer_destination_token_account);
        self
    }
    #[inline(always)]
    pub fn user_source_owner(&mut self, user_source_owner: solana_pubkey::Pubkey) -> &mut Self {
        self.user_source_owner = Some(user_source_owner);
        self
    }
    #[inline(always)]
    pub fn amount_in(&mut self, amount_in: u64) -> &mut Self {
        self.amount_in = Some(amount_in);
        self
    }
    #[inline(always)]
    pub fn minimum_amount_out(&mut self, minimum_amount_out: u64) -> &mut Self {
        self.minimum_amount_out = Some(minimum_amount_out);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = SwapBaseIn {
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            amm: self.amm.expect("amm is not set"),
            amm_authority: self.amm_authority.expect("amm_authority is not set"),
            amm_open_orders: self.amm_open_orders.expect("amm_open_orders is not set"),
            amm_target_orders: self.amm_target_orders,
            pool_coin_token_account: self
                .pool_coin_token_account
                .expect("pool_coin_token_account is not set"),
            pool_pc_token_account: self
                .pool_pc_token_account
                .expect("pool_pc_token_account is not set"),
            serum_program: self.serum_program.expect("serum_program is not set"),
            serum_market: self.serum_market.expect("serum_market is not set"),
            serum_bids: self.serum_bids.expect("serum_bids is not set"),
            serum_asks: self.serum_asks.expect("serum_asks is not set"),
            serum_event_queue: self
                .serum_event_queue
                .expect("serum_event_queue is not set"),
            serum_coin_vault_account: self
                .serum_coin_vault_account
                .expect("serum_coin_vault_account is not set"),
            serum_pc_vault_account: self
                .serum_pc_vault_account
                .expect("serum_pc_vault_account is not set"),
            serum_vault_signer: self
                .serum_vault_signer
                .expect("serum_vault_signer is not set"),
            uer_source_token_account: self
                .uer_source_token_account
                .expect("uer_source_token_account is not set"),
            uer_destination_token_account: self
                .uer_destination_token_account
                .expect("uer_destination_token_account is not set"),
            user_source_owner: self
                .user_source_owner
                .expect("user_source_owner is not set"),
        };
        let args = SwapBaseInInstructionArgs {
            amount_in: self.amount_in.clone().expect("amount_in is not set"),
            minimum_amount_out: self
                .minimum_amount_out
                .clone()
                .expect("minimum_amount_out is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `swap_base_in` CPI accounts.
pub struct SwapBaseInCpiAccounts<'a, 'b> {
    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub amm: &'b solana_account_info::AccountInfo<'a>,

    pub amm_authority: &'b solana_account_info::AccountInfo<'a>,

    pub amm_open_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_target_orders: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub pool_coin_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub pool_pc_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_program: &'b solana_account_info::AccountInfo<'a>,

    pub serum_market: &'b solana_account_info::AccountInfo<'a>,

    pub serum_bids: &'b solana_account_info::AccountInfo<'a>,

    pub serum_asks: &'b solana_account_info::AccountInfo<'a>,

    pub serum_event_queue: &'b solana_account_info::AccountInfo<'a>,

    pub serum_coin_vault_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_pc_vault_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,

    pub uer_source_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub uer_destination_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub user_source_owner: &'b solana_account_info::AccountInfo<'a>,
}

/// `swap_base_in` CPI instruction.
pub struct SwapBaseInCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub amm: &'b solana_account_info::AccountInfo<'a>,

    pub amm_authority: &'b solana_account_info::AccountInfo<'a>,

    pub amm_open_orders: &'b solana_account_info::AccountInfo<'a>,

    pub amm_target_orders: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub pool_coin_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub pool_pc_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_program: &'b solana_account_info::AccountInfo<'a>,

    pub serum_market: &'b solana_account_info::AccountInfo<'a>,

    pub serum_bids: &'b solana_account_info::AccountInfo<'a>,

    pub serum_asks: &'b solana_account_info::AccountInfo<'a>,

    pub serum_event_queue: &'b solana_account_info::AccountInfo<'a>,

    pub serum_coin_vault_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_pc_vault_account: &'b solana_account_info::AccountInfo<'a>,

    pub serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,

    pub uer_source_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub uer_destination_token_account: &'b solana_account_info::AccountInfo<'a>,

    pub user_source_owner: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SwapBaseInInstructionArgs,
}

impl<'a, 'b> SwapBaseInCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SwapBaseInCpiAccounts<'a, 'b>,
        args: SwapBaseInInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            token_program: accounts.token_program,
            amm: accounts.amm,
            amm_authority: accounts.amm_authority,
            amm_open_orders: accounts.amm_open_orders,
            amm_target_orders: accounts.amm_target_orders,
            pool_coin_token_account: accounts.pool_coin_token_account,
            pool_pc_token_account: accounts.pool_pc_token_account,
            serum_program: accounts.serum_program,
            serum_market: accounts.serum_market,
            serum_bids: accounts.serum_bids,
            serum_asks: accounts.serum_asks,
            serum_event_queue: accounts.serum_event_queue,
            serum_coin_vault_account: accounts.serum_coin_vault_account,
            serum_pc_vault_account: accounts.serum_pc_vault_account,
            serum_vault_signer: accounts.serum_vault_signer,
            uer_source_token_account: accounts.uer_source_token_account,
            uer_destination_token_account: accounts.uer_destination_token_account,
            user_source_owner: accounts.user_source_owner,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(18 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.amm.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.amm_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.amm_open_orders.key,
            false,
        ));
        if let Some(amm_target_orders) = self.amm_target_orders {
            accounts.push(solana_instruction::AccountMeta::new(
                *amm_target_orders.key,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_coin_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_pc_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.serum_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_market.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_bids.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_asks.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_event_queue.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_coin_vault_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.serum_pc_vault_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.serum_vault_signer.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.uer_source_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.uer_destination_token_account.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.user_source_owner.key,
            true,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = borsh::to_vec(&SwapBaseInInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::RAYDIUM_AMM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(19 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.amm.clone());
        account_infos.push(self.amm_authority.clone());
        account_infos.push(self.amm_open_orders.clone());
        if let Some(amm_target_orders) = self.amm_target_orders {
            account_infos.push(amm_target_orders.clone());
        }
        account_infos.push(self.pool_coin_token_account.clone());
        account_infos.push(self.pool_pc_token_account.clone());
        account_infos.push(self.serum_program.clone());
        account_infos.push(self.serum_market.clone());
        account_infos.push(self.serum_bids.clone());
        account_infos.push(self.serum_asks.clone());
        account_infos.push(self.serum_event_queue.clone());
        account_infos.push(self.serum_coin_vault_account.clone());
        account_infos.push(self.serum_pc_vault_account.clone());
        account_infos.push(self.serum_vault_signer.clone());
        account_infos.push(self.uer_source_token_account.clone());
        account_infos.push(self.uer_destination_token_account.clone());
        account_infos.push(self.user_source_owner.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `SwapBaseIn` via CPI.
///
/// ### Accounts:
///
///   0. `[]` token_program
///   1. `[writable]` amm
///   2. `[]` amm_authority
///   3. `[writable]` amm_open_orders
///   4. `[writable, optional]` amm_target_orders
///   5. `[writable]` pool_coin_token_account
///   6. `[writable]` pool_pc_token_account
///   7. `[]` serum_program
///   8. `[writable]` serum_market
///   9. `[writable]` serum_bids
///   10. `[writable]` serum_asks
///   11. `[writable]` serum_event_queue
///   12. `[writable]` serum_coin_vault_account
///   13. `[writable]` serum_pc_vault_account
///   14. `[]` serum_vault_signer
///   15. `[writable]` uer_source_token_account
///   16. `[writable]` uer_destination_token_account
///   17. `[signer]` user_source_owner
#[derive(Clone, Debug)]
pub struct SwapBaseInCpiBuilder<'a, 'b> {
    instruction: Box<SwapBaseInCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SwapBaseInCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SwapBaseInCpiBuilderInstruction {
            __program: program,
            token_program: None,
            amm: None,
            amm_authority: None,
            amm_open_orders: None,
            amm_target_orders: None,
            pool_coin_token_account: None,
            pool_pc_token_account: None,
            serum_program: None,
            serum_market: None,
            serum_bids: None,
            serum_asks: None,
            serum_event_queue: None,
            serum_coin_vault_account: None,
            serum_pc_vault_account: None,
            serum_vault_signer: None,
            uer_source_token_account: None,
            uer_destination_token_account: None,
            user_source_owner: None,
            amount_in: None,
            minimum_amount_out: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn amm(&mut self, amm: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.amm = Some(amm);
        self
    }
    #[inline(always)]
    pub fn amm_authority(
        &mut self,
        amm_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_authority = Some(amm_authority);
        self
    }
    #[inline(always)]
    pub fn amm_open_orders(
        &mut self,
        amm_open_orders: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.amm_open_orders = Some(amm_open_orders);
        self
    }
    /// `[optional account]`
    #[inline(always)]
    pub fn amm_target_orders(
        &mut self,
        amm_target_orders: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.amm_target_orders = amm_target_orders;
        self
    }
    #[inline(always)]
    pub fn pool_coin_token_account(
        &mut self,
        pool_coin_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_coin_token_account = Some(pool_coin_token_account);
        self
    }
    #[inline(always)]
    pub fn pool_pc_token_account(
        &mut self,
        pool_pc_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_pc_token_account = Some(pool_pc_token_account);
        self
    }
    #[inline(always)]
    pub fn serum_program(
        &mut self,
        serum_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_program = Some(serum_program);
        self
    }
    #[inline(always)]
    pub fn serum_market(
        &mut self,
        serum_market: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_market = Some(serum_market);
        self
    }
    #[inline(always)]
    pub fn serum_bids(
        &mut self,
        serum_bids: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_bids = Some(serum_bids);
        self
    }
    #[inline(always)]
    pub fn serum_asks(
        &mut self,
        serum_asks: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_asks = Some(serum_asks);
        self
    }
    #[inline(always)]
    pub fn serum_event_queue(
        &mut self,
        serum_event_queue: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_event_queue = Some(serum_event_queue);
        self
    }
    #[inline(always)]
    pub fn serum_coin_vault_account(
        &mut self,
        serum_coin_vault_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_coin_vault_account = Some(serum_coin_vault_account);
        self
    }
    #[inline(always)]
    pub fn serum_pc_vault_account(
        &mut self,
        serum_pc_vault_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_pc_vault_account = Some(serum_pc_vault_account);
        self
    }
    #[inline(always)]
    pub fn serum_vault_signer(
        &mut self,
        serum_vault_signer: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.serum_vault_signer = Some(serum_vault_signer);
        self
    }
    #[inline(always)]
    pub fn uer_source_token_account(
        &mut self,
        uer_source_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.uer_source_token_account = Some(uer_source_token_account);
        self
    }
    #[inline(always)]
    pub fn uer_destination_token_account(
        &mut self,
        uer_destination_token_account: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.uer_destination_token_account = Some(uer_destination_token_account);
        self
    }
    #[inline(always)]
    pub fn user_source_owner(
        &mut self,
        user_source_owner: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.user_source_owner = Some(user_source_owner);
        self
    }
    #[inline(always)]
    pub fn amount_in(&mut self, amount_in: u64) -> &mut Self {
        self.instruction.amount_in = Some(amount_in);
        self
    }
    #[inline(always)]
    pub fn minimum_amount_out(&mut self, minimum_amount_out: u64) -> &mut Self {
        self.instruction.minimum_amount_out = Some(minimum_amount_out);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let args = SwapBaseInInstructionArgs {
            amount_in: self
                .instruction
                .amount_in
                .clone()
                .expect("amount_in is not set"),
            minimum_amount_out: self
                .instruction
                .minimum_amount_out
                .clone()
                .expect("minimum_amount_out is not set"),
        };
        let instruction = SwapBaseInCpi {
            __program: self.instruction.__program,

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            amm: self.instruction.amm.expect("amm is not set"),

            amm_authority: self
                .instruction
                .amm_authority
                .expect("amm_authority is not set"),

            amm_open_orders: self
                .instruction
                .amm_open_orders
                .expect("amm_open_orders is not set"),

            amm_target_orders: self.instruction.amm_target_orders,

            pool_coin_token_account: self
                .instruction
                .pool_coin_token_account
                .expect("pool_coin_token_account is not set"),

            pool_pc_token_account: self
                .instruction
                .pool_pc_token_account
                .expect("pool_pc_token_account is not set"),

            serum_program: self
                .instruction
                .serum_program
                .expect("serum_program is not set"),

            serum_market: self
                .instruction
                .serum_market
                .expect("serum_market is not set"),

            serum_bids: self.instruction.serum_bids.expect("serum_bids is not set"),

            serum_asks: self.instruction.serum_asks.expect("serum_asks is not set"),

            serum_event_queue: self
                .instruction
                .serum_event_queue
                .expect("serum_event_queue is not set"),

            serum_coin_vault_account: self
                .instruction
                .serum_coin_vault_account
                .expect("serum_coin_vault_account is not set"),

            serum_pc_vault_account: self
                .instruction
                .serum_pc_vault_account
                .expect("serum_pc_vault_account is not set"),

            serum_vault_signer: self
                .instruction
                .serum_vault_signer
                .expect("serum_vault_signer is not set"),

            uer_source_token_account: self
                .instruction
                .uer_source_token_account
                .expect("uer_source_token_account is not set"),

            uer_destination_token_account: self
                .instruction
                .uer_destination_token_account
                .expect("uer_destination_token_account is not set"),

            user_source_owner: self
                .instruction
                .user_source_owner
                .expect("user_source_owner is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SwapBaseInCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_open_orders: Option<&'b solana_account_info::AccountInfo<'a>>,
    amm_target_orders: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_coin_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_pc_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_market: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_bids: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_asks: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_event_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_coin_vault_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_pc_vault_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    serum_vault_signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    uer_source_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    uer_destination_token_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    user_source_owner: Option<&'b solana_account_info::AccountInfo<'a>>,
    amount_in: Option<u64>,
    minimum_amount_out: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
