import { generateResolutionInputTypes } from '@codama/dynamic-address-resolution/codegen';
import type { RootNode } from 'codama';

import { generateInstructionBuildersMap } from './generate-instruction-builder';
import { generateSignerTypes } from './generate-signer-types';

/**
 * Generate a self-contained TypeScript file with all instruction types for a Codama IDL:
 * - Per-instruction `${Name}Args`, `${Name}Accounts`, `${Name}Resolvers`.
 * - Per-instruction `${Name}Signers` aliases.
 * - The aggregate `${Program}InstructionBuilders` map.
 */
export function generateTypes(idl: RootNode): string {
    return (
        INSTRUCTION_TYPES_FILE_HEADER +
        generateResolutionInputTypes(idl) +
        generateSignerTypes(idl) +
        generateInstructionBuildersMap(idl)
    );
}

const INSTRUCTION_TYPES_FILE_HEADER = `/**
 * Auto-generated instruction types
 * DO NOT EDIT - Generated by @codama/dynamic-instructions generate-types
 */

import type { Address } from '@solana/addresses';
import type { InstructionsBuilderFn } from '@codama/dynamic-instructions';

`;
