[package]
name = "codama-renderers-rust-e2e-meteora"
version = "0.0.0"
edition = "2021"

[features]
anchor = ["dep:anchor-lang"]
anchor-idl-build = ["anchor", "anchor-lang?/idl-build"]
serde = ["dep:serde", "dep:serde_with"]
test-sbf = []
fetch = ["dep:solana-client", "dep:solana-sdk"]

[dependencies]
anchor-lang = { version = "~0.30", optional = true }
borsh = "^0.10"
kaigan = "0.2.5"
num-derive = "^0.3"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-account = { version = "~2.2", optional = true }
solana-account-info = "~2.2"
solana-client = { version = "~2.2", optional = true }
solana-cpi = "~2.2"
solana-decode-error = "~2.3"
solana-instruction = "~2.3"
solana-program-error = "~2.2"
solana-pubkey = { version = "~2.2", features = ["curve25519"] }
solana-sdk = { version = "~2.3", optional = true }
thiserror = "^1.0"

[dev-dependencies]
assert_matches = "1.5.0"
solana-sdk = "~2.3"
