//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#amm_config;
pub(crate) mod r#fees;
pub(crate) mod r#last_order_distance;
pub(crate) mod r#need_take;
pub(crate) mod r#out_put_data;
pub(crate) mod r#swap_instruction_base_in;
pub(crate) mod r#swap_instruction_base_out;
pub(crate) mod r#target_order;
pub(crate) mod r#withdraw_dest_token;
pub(crate) mod r#withdraw_queue;

pub use self::r#amm_config::*;
pub use self::r#fees::*;
pub use self::r#last_order_distance::*;
pub use self::r#need_take::*;
pub use self::r#out_put_data::*;
pub use self::r#swap_instruction_base_in::*;
pub use self::r#swap_instruction_base_out::*;
pub use self::r#target_order::*;
pub use self::r#withdraw_dest_token::*;
pub use self::r#withdraw_queue::*;
