//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#amm_config;
pub(crate) mod r#amm_info;
pub(crate) mod r#fees;
pub(crate) mod r#target_orders;

pub use self::r#amm_config::*;
pub use self::r#amm_info::*;
pub use self::r#fees::*;
pub use self::r#target_orders::*;
