[package]
name = "codama-renderers-rust-e2e-dummy"
version = "0.0.0"
edition = "2021"

[features]
test-sbf = []

[dependencies]
pinocchio = "0.6"
pinocchio-pubkey = "0.2"

[dev-dependencies]
assert_matches = "1.5.0"
